[pytest]
testpaths = testcases
python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts =
    -v
    --tb=short
    --strict-markers
    --alluredir=report/allure-results

markers =
    # === 链路测试标记 ===
    link1: 链路1：新建
    link2: 链路2：新建、分发
    link3: 链路3：新建、分发、查询、暂存
    link4: 链路4：新建、分发、查询、暂存、提交
    link5: 链路5：新建、分发、查询、暂存、提交、生成子订单
    link6: 链路6：新建、分发、查询、暂存、提交、生成子订单、录费用
    link7: 链路7：新建、分发、查询、暂存、提交、生成子订单、录费用、资产推送审批
    link8: 链路8：新建、分发、查询、暂存、提交、生成子订单、录费用、资产推送审批、订单锁定审批
