[pytest]
testpaths = testcases
python_files = test_*.py
python_classes = Test*
python_functions = test_*

filterwarnings =
    ignore::urllib3.exceptions.InsecureRequestWarning

addopts =
    -v
    --tb=short
    --strict-markers
    --alluredir=report/allure-results

markers =
    # === 链路测试标记 ===
    link1: 链路1：新建
    link2: 链路2：新建、分发
    link3: 链路3：新建、分发、查询、暂存
    link4: 链路4：新建、分发、查询、暂存、提交
    link5: 链路5：新建、分发、查询、暂存、提交、生成子订单
    link6: 链路6：新建、分发、查询、暂存、提交、生成子订单、录费用
    link7: 链路7：新建、分发、查询、暂存、提交、生成子订单、录费用、资产推送审批
    link8: 链路8：新建、分发、查询、暂存、提交、生成子订单、录费用、资产推送审批、订单锁定审批
    link9: 链路9：新建、分发、查询、暂存、提交、生成子订单、录费用、资产推送审批、订单锁定审批、未放款开票申请审批
    link10: 链路10：新建、分发、查询、暂存、提交、生成子订单、录费用、资产推送审批、订单锁定审批、未放款开票申请审批、供应商垫付申请审批
    link11: 链路11：新建、分发、查询、暂存、提交、生成子订单、录费用、资产推送审批、订单锁定审批、未放款开票申请审批、供应商垫付申请审批、生成费用通知单
    link12: 链路12：新建、分发、查询、暂存、提交、生成子订单、录费用、资产推送审批、订单锁定审批、未放款开票申请审批、供应商垫付申请审批、生成费用通知单、生成费用确认单
    link13: 链路13：新建...生成费用确认单、发起应收对账批次
    link14: 链路14：新建...发起应收对账批次、确认应收对账
    link15: 链路15：新建...确认应收对账、发起应收开票批次审批
    link16: 链路16：新建...发起应收开票批次审批、审核生成开票申请
    link17: 链路17：新建...审核生成开票申请、发票上传与登记
    link18: 链路18：新建...发票上传与登记、应收核销
    link19: 链路19：新建...应收核销、发起应付对账批次
    link20: 链路20：新建...确认应付对账
    link21: 链路21：新建...确认应付对账、发起应付开票批次申请
    link22: 链路22：新建...发起应付开票批次申请、应付发票上传与登记
    link23: 链路23：新建...应付发票上传与登记、发起付款需求
    link24: 链路24：新建...发起付款需求、审核生成付款单
