[pytest]
testpaths =
    testcases/order
    testcases/pay_receive
    testcases/receive_pay
python_files = test_*.py
python_classes = Test*
python_functions = test_*

filterwarnings =
    ignore::urllib3.exceptions.InsecureRequestWarning

addopts =
    -v
    --tb=short
    --strict-markers
    --alluredir=report/allure-results

markers =
    # 仅订单（新编号）
    order1: 链路1：新建
    order2: 链路2：分发
    order3: 链路3：暂存
    order4: 链路4：提交
    order5: 链路5：生成子订单
    order6: 链路6：录费用
    order7: 链路7：资产推送审批
    order8: 链路8：订单锁定审批
    order9: 链路9：未放款开票申请审批
    order10: 链路10：供应商垫付申请审批
    order11: 链路11：生成费用通知单
    order12: 链路12：生成费用确认单

    # 订单+应付（默认）
    order_pay_receive1: 链路1：发起应付对账批次
    order_pay_receive2: 链路2：确认应付对账
    order_pay_receive3: 链路3：发起应付开票批次申请
    order_pay_receive4: 链路4：应付发票上传与登记
    order_pay_receive5: 链路5：发起付款需求
    order_pay_receive6: 链路6：审核生成付款单
    order_pay_receive7: 链路7：付款单核销

    # 订单+应付+应收（默认）
    order_pay_receive8: 链路8：发起应收对账批次
    order_pay_receive9: 链路9：确认应收对账
    order_pay_receive10: 链路10：发起应收开票批次审批
    order_pay_receive11: 链路11：审核生成开票申请
    order_pay_receive12: 链路12：发票上传与登记
    order_pay_receive13: 链路13：应收核销

    # 订单+应收（扩展）
    order_receive_pay1: 链路1：发起应收对账批次
    order_receive_pay2: 链路2：确认应收对账
    order_receive_pay3: 链路3：发起应收开票批次审批
    order_receive_pay4: 链路4：审核生成开票申请
    order_receive_pay5: 链路5：发票上传与登记
    order_receive_pay6: 链路6：应收核销

    # 订单+应收+应付（扩展）
    order_receive_pay7: 链路7：发起应付对账批次
    order_receive_pay8: 链路8：确认应付对账
    order_receive_pay9: 链路9：发起应付开票批次申请
    order_receive_pay10: 链路10：应付发票上传与登记
    order_receive_pay11: 链路11：发起付款需求
    order_receive_pay12: 链路12：审核生成付款单
    order_receive_pay13: 链路13：付款单核销
